# Generated by Django 5.0.6 on 2024-07-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customers_options_customers_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('order',), 'verbose_name': 'Customers'},
        ),
    ]
